name: Pull Request Checks

on:
  pull_request:
    branches: [development, production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      - name: Print connection string
      run: echo "Connection String: Server=localhost;Port=3306;Database=Cleandb;User=root;Password=12345;"

    - name: Build and deploy
      run: |
        # Your build and deploy steps here


      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Format the code
        run: dotnet format --verbosity diagnostic --verify-no-changes

      - name: Restore dependencies
        run: dotnet restore --disable-parallel

      - name: Build the solution
        run: dotnet build --no-restore

      - name: Run all tests
        run: dotnet test --no-build --verbosity normal --no-restore
